apiVersion: v1
kind: Secret
metadata:
  name: prod-mongo-secret
  namespace: prod-mongo
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: TU9OR09fSU5JVERCX1JPT1RfVVNFUk5BTUU=
  MONGO_INITDB_ROOT_PASSWORD: TU9OR09fSU5JVERCX1JPT1RfUEFTU1dPUkQ=